package exception_handlingpack;

public class Main {

	public static void main(String[] args) {
		int a=10;
		int b=0;
		int c;
		
		try {
			c=a/b;
		}
		catch(Exception e)
		{
			System.out.println("fd");
		}
		try
		{
			int arr[]=null;
			System.out.print(arr[1]);
		}
		
		catch(ArithmeticException e)
		{
			System.out.println("ERrro accured");
		}
		
		
	}

}
